version: "3.9"

services:
  atl-train-tracker-backend:
    container_name: atl-train-tracker-backend
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
